name: my_portfolio
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Run Os 
    runs-on: self-hosted

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install all Dependency
          run: npm install

        - name: build project
          run: npm run build

        



   



  
