name: my_portfolio
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Run Os 
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install all Dependency
          run: npm install

        - name: Install  yarn packages
          run: npm install --global yarn
           
        - name: Image Optimization 
          run: yarn add sharp

        



   



  
